apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ujo32g1yi-python 
  janus-idp.io/tekton: ujo32g1yi-python
  backstage.io/kubernetes-id: ujo32g1yi-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ujo32g1yi-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  